add flags

diff --git a/make-centos-bootstick b/make-centos-bootstick
--- a/make-centos-bootstick
+++ b/make-centos-bootstick
@@ -2,12 +2,12 @@
 
 # Insert a usb stick (at least 1G) into a CentOS 7 machine.
 # yum -y install syslinux screen dosfstools
-# put your kickstart in $PWD and name it ks.cfg
+# Any custom kickstart or syslinux.cfg need to be in your $PWD
 # Run this script as root, passing the /dev/sdX you are going to use
 # eg:
 #   sudo ./make-centos-bootstick /dev/sdb
-
-# This probably works for and on any RedHat based distro, but has not been tested.
+# This probably works for and on any RedHat based distro,
+# but has only been tested with CentOS 7.
 
 # LICENSE
 # MIT License
@@ -18,7 +18,6 @@
 # More complete cleanup
 # Flag to not cleanup
 
-dev=$1
 tmp_dir="./bootstick"
 # Since the mbr.bin is kept in different places in different versions.
 mbr=$(rpm -ql syslinux | grep '/mbr.bin$')
@@ -26,6 +25,8 @@ mirror=http://mirrors.cmich.edu/centos/7/isos/x86_64
 iso=CentOS-7-x86_64-NetInstall-1503.iso
 md5sum=md5sum.txt
 ks=ks.cfg
+usage="USAGE: $0 [-r REMOTE_KS ] [-k LOCAL_KS] [-s CUSTOM_SYSLINUX] [-i ISO] \
+[-u ISO_URL] [--no-clean] DEVICE"
 
 warn() {
     echo "$@" >&2
@@ -88,13 +89,16 @@ mount_parts() {
 make_boot() {
     cp -v DVD/isolinux/* BOOT/
     mv -v BOOT/isolinux.cfg BOOT/syslinux.cfg
-    edit_syslinux
-    cp -v $ks BOOT/ || die 16 "Couldn't copy $ks to BOOT/"
-    
+    if [ -n "$syslinux"]; then
+        mv -v $syslinux BOOT/syslinux.cfg \
+        || die 1 "couldn't move $syslinux to Boot/"
+    else
+        edit_syslinux
+    fi
 }
 
 make_data() {
-    cp -v $iso DATA/
+    mv -v $iso DATA/ || die 1 "couldn't move $iso to DATA/"
 }
 
 clean_up() {
@@ -104,10 +108,62 @@ clean_up() {
 }
 
 edit_syslinux() {
-    sed -i \
-    '/label linux/,/^$/s#LABEL=.* quiet#LABEL=DATA:/ ks=hd:LABEL=BOOT:/ks.cfg#' \
-    BOOT/syslinux.cfg
+    if [ -n "$ksremote" ]; then
+        sed -i \
+        '/label linux/,/^$/s#LABEL=.* quiet#LABEL=DATA:/ '"$ks"'#'
+        BOOT/syslinux.cfg
+    elif [ -n "$ks" ]; then
+        sed -i \
+        '/label linux/,/^$/s#LABEL=.* quiet#LABEL=DATA:/ ks=hd:LABEL=BOOT:/ks.cfg#' \
+        BOOT/syslinux.cfg
+        mv -v $ks BOOT/ || die 16 "Couldn't move $ks to BOOT/"
+    else
+        sed -i \
+        '/label linux/,/^$/s#LABEL=.* quiet#LABEL=DATA:/#' \
+        BOOT/syslinux.cfg
+    fi
 }
+
+while [ $# -gt 0 ]; do
+    case $1 in
+      -h)
+        die 0 $usage
+        ;;
+      -r)
+        ks=$2
+        ksremote=true
+        shift 2
+        ;;
+      -s)
+        syslinux=$2
+        cp $syslinux $tmp_dir
+        shift 2
+        ;;
+      -k)
+        ks=$2
+        cp $ks $tmp_dir
+        shift 2
+        ;;
+      --no-clean)
+        noclean=true
+        shift
+        ;;
+      --)
+        shift
+        break
+        ;;
+      -*)
+        die 4 Unknown flag $1 $usage
+        break
+        ;;
+      *)
+        break
+        ;;
+    esac
+done
+
+test $# -eq 1 || die 1 "$usage"
+dev=$1
 
 mkdir -p $tmp_dir || die 2 "Can't make $tmp_dir"
 cp -v $ks $tmp_dir/ || die 32 "Can't copy $ks to $tmp_dir"
@@ -122,4 +178,4 @@ install_syslinux
 mount_parts
 make_boot
 make_data
-clean_up
+test "$noclean" || clean_up
